/**
 * CLOUDINARY IMAGE MAPPING
 * 
 * This file is auto-generated during migration to Cloudinary.
 * It maps local asset paths to their Cloudinary CDN counterparts.
 */

export const IMAGE_MAPPING: Record<string, string> = {
  "public/images/Ellipse_3.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355894/sen_web/static/public/images/Ellipse_3.png",
  "/images/Ellipse_3.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355894/sen_web/static/public/images/Ellipse_3.png",
  "public/images/Ellipse_4.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355899/sen_web/static/public/images/Ellipse_4.png",
  "/images/Ellipse_4.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355899/sen_web/static/public/images/Ellipse_4.png",
  "public/images/Ellipse_5.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355906/sen_web/static/public/images/Ellipse_5.png",
  "/images/Ellipse_5.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355906/sen_web/static/public/images/Ellipse_5.png",
  "public/images/Game.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355915/sen_web/static/public/images/Game.jpg",
  "/images/Game.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355915/sen_web/static/public/images/Game.jpg",
  "public/images/Image.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355923/sen_web/static/public/images/Image.png",
  "/images/Image.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355923/sen_web/static/public/images/Image.png",
  "public/images/MapGame.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355929/sen_web/static/public/images/MapGame.jpg",
  "/images/MapGame.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355929/sen_web/static/public/images/MapGame.jpg",
  "public/images/Zero_home.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355946/sen_web/static/public/images/Zero_home.jpg",
  "/images/Zero_home.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355946/sen_web/static/public/images/Zero_home.jpg",
  "public/images/hoatiettrongdong.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355964/sen_web/static/public/@/assets/images/background/Hoatiettrongdong.png",
  "/images/hoatiettrongdong.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355964/sen_web/static/public/@/assets/images/background/Hoatiettrongdong.png",
  "public/images/zero_others.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355977/sen_web/static/public/images/zero_others.png",
  "/images/zero_others.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355977/sen_web/static/public/images/zero_others.png",
  "src/assets/images/background/background-full.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774355993/sen_web/static/src/assets/images/background/background-full.jpg",
  "src/assets/images/background/background-nothing.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356010/sen_web/static/src/assets/images/background/background-nothing.jpg",
  "src/assets/images/background/background-red.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356021/sen_web/static/src/assets/images/background/background-red.jpg",
  "src/assets/images/background/bird.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356024/sen_web/static/src/assets/images/background/bird.png",
  "src/assets/images/background/bronze-drum.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356033/sen_web/static/src/assets/images/background/bronze-drum.png",
  "src/assets/images/background/leaf.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356037/sen_web/static/src/assets/images/background/leaf.png",
  "src/assets/images/background/lotus-1.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356040/sen_web/static/src/assets/images/background/lotus-1.png",
  "src/assets/images/background/lotus-2.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356043/sen_web/static/src/assets/images/background/lotus-2.png",
  "src/assets/images/background/lotus-3.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356045/sen_web/static/src/assets/images/background/lotus-3.png",
  "src/assets/images/background/senhoacum.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356048/sen_web/static/src/assets/images/background/senhoacum.png",
  "src/assets/images/background/smoke-left.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356055/sen_web/static/src/assets/images/background/smoke-left.png",
  "src/assets/images/background/smoke-right.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356059/sen_web/static/src/assets/images/background/smoke-right.png",
  "src/assets/images/character/bag.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356062/sen_web/static/src/assets/images/character/bag.png",
  "src/assets/images/character/coats.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356068/sen_web/static/src/assets/images/character/coats.png",
  "src/assets/images/character/dress.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356072/sen_web/static/src/assets/images/character/dress.png",
  "src/assets/images/character/eyebrow_1.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356074/sen_web/static/src/assets/images/character/eyebrow_1.png",
  "src/assets/images/character/eyebrow_2.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356076/sen_web/static/src/assets/images/character/eyebrow_2.png",
  "src/assets/images/character/eyes_closed.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356077/sen_web/static/src/assets/images/character/eyes_closed.png",
  "src/assets/images/character/eyes_half.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356078/sen_web/static/src/assets/images/character/eyes_half.png",
  "src/assets/images/character/eyes_open.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356080/sen_web/static/src/assets/images/character/eyes_open.png",
  "src/assets/images/character/glasses.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356081/sen_web/static/src/assets/images/character/glasses.png",
  "src/assets/images/character/hair_back.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356084/sen_web/static/src/assets/images/character/hair_back.png",
  "src/assets/images/character/hair_front.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356087/sen_web/static/src/assets/images/character/hair_front.png",
  "src/assets/images/character/hand_left.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356089/sen_web/static/src/assets/images/character/hand_left.png",
  "src/assets/images/character/hand_right.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356091/sen_web/static/src/assets/images/character/hand_right.png",
  "src/assets/images/character/hat.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356093/sen_web/static/src/assets/images/character/hat.png",
  "src/assets/images/character/hat_accessories_1.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356094/sen_web/static/src/assets/images/character/hat_accessories_1.png",
  "src/assets/images/character/hat_accessories_2.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356096/sen_web/static/src/assets/images/character/hat_accessories_2.png",
  "src/assets/images/character/hat_accessories_3.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356097/sen_web/static/src/assets/images/character/hat_accessories_3.png",
  "src/assets/images/character/head_base.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356105/sen_web/static/src/assets/images/character/head_base.png",
  "src/assets/images/character/inner_shirt.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356139/sen_web/static/src/assets/images/character/inner_shirt.png",
  "src/assets/images/character/leg.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356143/sen_web/static/src/assets/images/character/leg.png",
  "src/assets/images/character/mouth_angry.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356144/sen_web/static/src/assets/images/character/mouth_angry.png",
  "src/assets/images/character/mouth_close.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356145/sen_web/static/src/assets/images/character/mouth_close.png",
  "src/assets/images/character/mouth_half.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356147/sen_web/static/src/assets/images/character/mouth_half.png",
  "src/assets/images/character/mouth_open.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356148/sen_web/static/src/assets/images/character/mouth_open.png",
  "src/assets/images/character/mouth_sad.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356149/sen_web/static/src/assets/images/character/mouth_sad.png",
  "src/assets/images/character/mouth_smile.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356150/sen_web/static/src/assets/images/character/mouth_smile.png",
  "src/assets/images/character/ribbon_inner_shirt.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356151/sen_web/static/src/assets/images/character/ribbon_inner_shirt.png",
  "src/assets/images/character/ribbon_shoes.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356154/sen_web/static/src/assets/images/character/ribbon_shoes.png",
  "src/assets/images/character/shirt_accessories.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356156/sen_web/static/src/assets/images/character/shirt_accessories.png",
  "src/assets/images/character/shoes.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356167/sen_web/static/src/assets/images/character/shoes.png",
  "src/assets/images/character/whites_of_the_eyes.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356180/sen_web/static/src/assets/images/character/whites_of_the_eyes.png",
  "src/assets/images/SenChibi/arm_hello.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356182/sen_web/static/src/assets/images/SenChibi/arm_hello.png",
  "src/assets/images/SenChibi/arm_left.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356184/sen_web/static/src/assets/images/SenChibi/arm_left.png",
  "src/assets/images/SenChibi/arm_right.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356186/sen_web/static/src/assets/images/SenChibi/arm_right.png",
  "src/assets/images/SenChibi/clothers_ao_dai.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356190/sen_web/static/src/assets/images/SenChibi/clothers_ao_dai.png",
  "src/assets/images/SenChibi/clothers_normal.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356195/sen_web/static/src/assets/images/SenChibi/clothers_normal.png",
  "src/assets/images/SenChibi/coats.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356199/sen_web/static/src/assets/images/SenChibi/coats.png",
  "src/assets/images/SenChibi/eye.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356201/sen_web/static/src/assets/images/SenChibi/eye.png",
  "src/assets/images/SenChibi/eye_Like.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356203/sen_web/static/src/assets/images/SenChibi/eye_Like.png",
  "src/assets/images/SenChibi/eye_blink.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356205/sen_web/static/src/assets/images/SenChibi/eye_blink.png",
  "src/assets/images/SenChibi/eye_close.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356206/sen_web/static/src/assets/images/SenChibi/eye_close.png",
  "src/assets/images/SenChibi/eye_half.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356207/sen_web/static/src/assets/images/SenChibi/eye_half.png",
  "src/assets/images/SenChibi/eye_sleep.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356209/sen_web/static/src/assets/images/SenChibi/eye_sleep.png",
  "src/assets/images/SenChibi/face.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356213/sen_web/static/src/assets/images/SenChibi/face.png",
  "src/assets/images/SenChibi/glasses.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356215/sen_web/static/src/assets/images/SenChibi/glasses.png",
  "src/assets/images/SenChibi/hair_back.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356220/sen_web/static/src/assets/images/SenChibi/hair_back.png",
  "src/assets/images/SenChibi/hair_font.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356235/sen_web/static/src/assets/images/SenChibi/hair_font.png",
  "src/assets/images/SenChibi/hair_top.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356237/sen_web/static/src/assets/images/SenChibi/hair_top.png",
  "src/assets/images/SenChibi/hand_back.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356239/sen_web/static/src/assets/images/SenChibi/hand_back.png",
  "src/assets/images/SenChibi/hand_flag.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356241/sen_web/static/src/assets/images/SenChibi/hand_flag.png",
  "src/assets/images/SenChibi/hand_like.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356243/sen_web/static/src/assets/images/SenChibi/hand_like.png",
  "src/assets/images/SenChibi/hand_point.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356245/sen_web/static/src/assets/images/SenChibi/hand_point.png",
  "src/assets/images/SenChibi/hat.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356250/sen_web/static/src/assets/images/SenChibi/hat.png",
  "src/assets/images/SenChibi/legs.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356253/sen_web/static/src/assets/images/SenChibi/legs.png",
  "src/assets/images/SenChibi/mouth_close.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356255/sen_web/static/src/assets/images/SenChibi/mouth_close.png",
  "src/assets/images/SenChibi/mouth_half.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356256/sen_web/static/src/assets/images/SenChibi/mouth_half.png",
  "src/assets/images/SenChibi/mouth_open.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356257/sen_web/static/src/assets/images/SenChibi/mouth_open.png",
  "src/assets/images/SenChibi/mouth_sad.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356258/sen_web/static/src/assets/images/SenChibi/mouth_sad.png",
  "src/assets/images/SenChibi/mouth_smile.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356260/sen_web/static/src/assets/images/SenChibi/mouth_smile.png",
  "src/assets/images/SenChibi/mouth_smile_2.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356260/sen_web/static/src/assets/images/SenChibi/mouth_smile_2.png",
  "src/assets/images/SenChibi/mouth_tongue.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356261/sen_web/static/src/assets/images/SenChibi/mouth_tongue.png",
  "src/pages/Poster/Photo/Duy.JPG": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774356936/sen_web/static/src/pages/Poster/Photo/Duy.jpg",
  "src/pages/Poster/Photo/Hieu.JPG": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357030/sen_web/static/src/pages/Poster/Photo/Hieu.jpg",
  "src/pages/Poster/Photo/Nguyet.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357034/sen_web/static/src/pages/Poster/Photo/Nguyet.jpg",
  "src/pages/Poster/Photo/Tuan.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357064/sen_web/static/src/pages/Poster/Photo/Tuan.jpg",
  "src/pages/Poster/Photo/Yen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357068/sen_web/static/src/pages/Poster/Photo/Yen.jpg",
  "src/pages/Poster/ImageProd/Mockup.webp": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774359072/sen_web/static/src/pages/Poster/ImageProd/Mockup.jpg",
  "src/pages/Poster/ImageProd/Mockup.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774359072/sen_web/static/src/pages/Poster/ImageProd/Mockup.jpg",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 222400.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357094/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20222400.jpg",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 222450.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357111/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20222450.jpg",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 222549.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357121/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20222549.png",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 222557.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357134/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20222557.jpg",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 222626.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357149/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20222626.jpg",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 223208.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357164/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20223208.jpg",
  "src/pages/Poster/ImageProd/Desk/Screenshot 2026-03-09 230403.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357184/sen_web/static/src/pages/Poster/ImageProd/Desk/Screenshot%202026-03-09%20230403.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222744_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357272/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222744_sen.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222751_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357285/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222751_sen.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222759_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357296/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222759_sen.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222805_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357302/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222805_sen.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222815_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357310/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222815_sen.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222853_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357320/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222853_sen.jpg",
  "src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222854_sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357331/sen_web/static/src/pages/Poster/ImageProd/Phone/Screenshot_20260309_222854_sen.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260308_235654_host.exp.exponent-2.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357337/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260308_235654_host.exp.exponent-2.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222938_com.anonymous.sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357346/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222938_com.anonymous.sen.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222945_com.anonymous.sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357353/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222945_com.anonymous.sen.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222947_com.anonymous.sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357358/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222947_com.anonymous.sen.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222954_com.anonymous.sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357363/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260309_222954_com.anonymous.sen.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260309_223005_com.anonymous.sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357367/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260309_223005_com.anonymous.sen.jpg",
  "src/pages/Poster/ImageProd/Tab/Screenshot_20260309_223012_com.anonymous.sen.jpg": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774357371/sen_web/static/src/pages/Poster/ImageProd/Tab/Screenshot_20260309_223012_com.anonymous.sen.jpg",
  "./ImageProd/Mockup.webp": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774359072/sen_web/static/src/pages/Poster/ImageProd/Mockup.jpg",
  "./ImageProd/Mockup.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774359072/sen_web/static/src/pages/Poster/ImageProd/Mockup.jpg",
  "src/assets/images/logo.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774362654/sen_web/static/src/assets/images/logo.png",
  "src/assets/images/logo2.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774362654/sen_web/static/src/assets/images/logo2.png",
  "../../assets/images/logo.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774362654/sen_web/static/src/assets/images/logo.png",
  "../../assets/images/logo2.png": "https://res.cloudinary.com/dmqb5l6bw/image/upload/f_auto,q_auto/v1774362654/sen_web/static/src/assets/images/logo2.png",
};